### ISSUE TITLE
Works for single server?

### ISSUE THREAD

**Issue by abbottjlu** [mknoxnv/ubuntu-slurm#10]
In case I have only ONE server, 
with torque + moab, this server can work as both pbs_server and pbs_client. 

Can I configure slurm in this way, namely, to run slurmd, slurmctrld, slurmdbd on the same server?

**Comment by mknoxnv** [comment]
This is possible but not something I have personally done.  You may want to consider running a VM to act as the login/slurmctrld/slurmdbd node.
