### ISSUE TITLE
Will this work for a single node?

### ISSUE THREAD

**Issue by brando90** [mknoxnv/ubuntu-slurm#11]
Will this work for a single node? I want to use that node with slurm

**Comment by mknoxnv** [comment]
You want to set up a single node cluster?

**Comment by maleorderbride** [comment]
I would like to know the answer to this as well. Yes, I wanted mgmt and compute on the same hardware. 

If this is really not feasible then what is the minimum hardware I could install as the mgmt head node? The compute is 2x20-core Intel 6148 & 384GBs RAM.

**Comment by mknoxnv** [comment]
I would suggest you set up a VM on your compute node to run the mgmt node.  The resource requirements are quite low and for a single node cluster you don't need dedicated hardware.
