### ISSUE TITLE
slurmdb pass in slurm.conf

### ISSUE THREAD

**Issue by nateGeorge** [mknoxnv/ubuntu-slurm#13]
In the instructions you have:

```
Edit /storage/ubuntu-slurm/slurm.conf and replace AccountingStoragePass=slurmdbpass with the DB password 
you used in the above SQL section.
$ cp ubuntu-slurm/slurm.conf /etc/slurm/
```

But the line in slurm.conf looks like:

`AccountingStoragePass=/var/run/munge/munge.socket.2`

It seems to work with the line as above.  I can create users and slurm works.

**Comment by mknoxnv** [comment]
Good point.  Thanks.  Updated README.md.
