### ISSUE TITLE
Can I use this if my nodes will be Virtual Machines without GPUs?

### ISSUE THREAD

**Issue by dwschulze** [mknoxnv/ubuntu-slurm#15]
I'm doing my first slurm installation and wanted to use this to create a cluster.  My controller and nodes will be VMs without GPUs.  Will this work for VMs without GPUs?

For that matter does slurm require that the nodes be real hardware with GPUs?  The docs on schedmd assume that you already have a cluster so they're not much help in getting started.

**Comment by mknoxnv** [comment]
Sure.  This would work on a cluster of VMs (with or without GPUs).  If you should remove the GresTypes line in slurm.conf.
