### ISSUE TITLE
Unable to start slurmd

### ISSUE THREAD

**Issue by IvantheDugtrio** [mknoxnv/ubuntu-slurm#2]
Following the guide on Ubuntu 16.04 LTS I'm able to get slurmdbd and slurmctld up and running however the slurmd always exits with no error message when I try to start it, only saying that it failed to start. Does slurmd need to be run by the slurm user or can it be started by root?

**Comment by StefanBiermann** [comment]
Had a similar problem - check /var/log/slurmd.log for more info. It may be the case that it is missing a library. Just do the configure in the beginning with:

./configure --prefix=/tmp/slurm-build --sysconfdir=/share/applications/etc/slurm --enable-pam --with-pam_dir=/lib/x86_64-linux-gnu/security/ --without-shared-libslurm

and go on as in the tutorial.
