### ISSUE TITLE
Slurm download link is not working

### ISSUE THREAD

**Issue by bhavindarji** [mknoxnv/ubuntu-slurm#6]
Hello, 
slurm download link is not working. Manually downloaded the tar file version 17.11.12. For this version it required another file cgroup_allowed_devices_file.conf in /etc/slurm/ directory on compute node.

By following the steps I am successfully able to configure slurm but when I run the sbatch command the dot out file is generated on the compute node - linux1 instead of slurm-ctrl, is that correct or it should be on control node?
I also wanted to learn about slurm user policies, please guide me...
Thank you.

**Comment by mknoxnv** [comment]
By default the output from a job will be written into the directory from which you submitted the job.  A good start would be to have a single filesystem that is shared across the login and compute nodes.  For example, /home or /scratch...

With regards to user policies.  What are you looking to do?  Restrict users from nodes, max number of jobs, etc?

**Comment by mknoxnv** [comment]
In that case you will want to look at slurm's QOS options.
https://slurm.schedmd.com/qos.html

For example: sacctmgr create qos myqos set MaxTRESPU=nodes=1

Will create a QOS called myqos which limits users to allocating only a single node at a time.  Users can submit additional jobs but they will stayed queued.  This is a reasonable way to ensure that a single user can submit lots of jobs but they won't consume the entire cluster.

**Comment by bhavindarji** [comment]
Thank you, that is very nice option, actually I was thinking of creating "reservation" scheme but this will work too.
One more thing to ask... In the slurm configuration step, why are you using "/tmp/slurm-build" as prefix instead of /usr or default location? 
Is it okay to use "checkinstall" tool to build deb package? you are using fpm
