### ISSUE TITLE
Unable to share GPU

### ISSUE THREAD

**Issue by feitiandemiaomi** [mknoxnv/ubuntu-slurm#7]
According to the guide, I suceeded in using GPU, but I found one problem that multiple tasks can't share uising GPU, I did not know what the problem is.

**Comment by mknoxnv** [comment]
Sounds like MPS is perhaps what you're looking for?  If so, let me know.

https://docs.nvidia.com/deploy/pdf/CUDA_Multi_Process_Service_Overview.pdf

**Comment by feitiandemiaomi** [comment]
@mknoxnv Thanks for your reply, maybe my expression is not accurate enough. I'd like to run multiple deeplearning jobs in one GPU card, but it failed, and always performed on different cards, like
![default](https://user-images.githubusercontent.com/18325462/49569465-f52ebd80-f96e-11e8-92f0-18ed2673b053.png) , I try to add "no_consume" in slurm.conf of version 18.08 , but it's aslo useless. 
   I once used Kubernetes with GPU ,which can share  one GPU card. So I doubt whether  the slurm can support sharing with one card. 
 Hope to get your help.

**Comment by mknoxnv** [comment]
Slurm will assign one GPU per job.  So if you submit four jobs they will be placed on the four different GPU cards.  A fifth job will sit in the queue until one of the four jobs finishes.  In your job submission script you could start multiple processes, those processes will only see the single GPU that was assigned to your job.  
Can you post an example job submission script that you used to launch the darknet processes?

**Comment by feitiandemiaomi** [comment]
I see,  you help me a lot. My script is as follows:
#!/bin/sh
#SBATCH -N 1      # nodes requested
#SBATCH -o outfile  # send stdout to outfile
#SBATCH -e errfile  # send stderr to errfile
#SBATCH -p compute
#SBATCH --gres=gpu:1
#SBATCH -a 0,2
#SBATCH --ntasks-per-node=4
#SBATCH --overcommit
./darknet
the multiple processes you said just like MPI ?  could you provide an example? And a good news is I find that darknet's code forces to use No. 0 graphics card , so I modify my script like
#!/bin/sh
#SBATCH -N 1      # nodes requested
#SBATCH -o outfile  # send stdout to outfile
#SBATCH -e errfile  # send stderr to errfile
#SBATCH -p compute
#SBATCH -a 0,2
#SBATCH --ntasks-per-node=4
#SBATCH --overcommit
./darknet  
the result are normal 
![default](https://user-images.githubusercontent.com/18325462/49624739-a71cc700-fa0d-11e8-999c-5ead7c092a86.png)

**Comment by Pastafarianist** [comment]
So does Slurm not support sharing GPUs between jobs, similarly to [LSF's `mode=shared`](https://www.ibm.com/support/knowledgecenter/en/SSWRJV_10.1.0/lsf_command_ref/bsub.gpu.1.html)?

**Comment by feitiandemiaomi** [comment]
@Pastafarianist  Do you mean slurm does not support shared resource ，it is only exclusive

**Comment by mknoxnv** [comment]
Slurm can assign jobs to particular GPUs on a node.  Multiple jobs per node.  Slurm will not assign multiple jobs to the same GPU hardware.  This is documented under generic resource scheduling (GRES).  https://slurm.schedmd.com/gres.html

**Comment by feitiandemiaomi** [comment]
@mknoxnv I see, this is why I can't assign extra GPU jobs to the same graphics card. I take it for granted that it can be the same as CPU jobs.
